export const coinsArr = [
  "ETHBTC",
  "LTCBTC",
  "BNBBTC",
  "NEOBTC",
  "QTUMETH",
  "EOSETH",
  "SNTETH",
  "BNTETH",
  "GASBTC",
  "BNBETH",
  "BTCUSDT",
  "ETHUSDT",
  "OAXETH",
  "MCOETH",
  "MCOBTC",
  "WTCBTC",
  "LRCBTC",
  "LRCETH",
  "QTUMBTC",
  // "OMGBTC",
  // "ZRXBTC",
  // "STRATBTC",
  // "SNGLSBTC",
  // "BQXBTC",
  // "KNCBTC",
  // "FUNBTC",
  // "FUNETH",
  // "SNMBTC",
  // "NEOETH",
  // "IOTABTC",
  // "IOTAETH",
  // "LINKBTC",
  // "LINKETH",
  // "XVGETH",
  // "SALTETH",
  // "MDAETH",
  // "MTLBTC",
  // "MTLETH",
  // "SUBETH",
  // "EOSBTC",
  // "SNTBTC",
  // "ETCETH",
  // "ETCBTC",
  // "MTHETH",
  // "ENGETH",
  // "ZECBTC",
  // "ZECETH",
  // "BNTBTC",
  // "ASTBTC",
  // "DASHBTC",
  // "DASHETH",
  // "OAXBTC",
  // "BTGBTC",
  // "EVXBTC",
  // "REQBTC",
  // "VIBBTC",
  // "HSRETH",
  // "TRXBTC",
  // "TRXETH",
  // "POWRBTC",
  // "POWRETH",
  // "ARKETH",
  // "XRPBTC",
  // "XRPETH",
  // "MODETH",
  // "ENJBTC",
  // "ENJETH",
  // "STORJBTC",
  // "BNBUSDT",
  // "YOYOBNB",
  // "VENBTC",
  // "KMDBTC",
  // "NULSBNB",
  // "RCNETH",
  // "NULSBTC",
  // "RDNBTC",
  // "RDNBNB",
  // "XMRBTC",
  // "XMRETH",
  // "WTCBNB",
  // "DLTETH",
  // "AMBBTC",
  // "AMBBNB",
  // "BCCUSDT",
  // "BATBTC",
  // "BATETH",
  // "BCPTBTC",
  // "BCPTBNB",
  // "ARNETH",
  // "GVTETH",
  // "CDTETH",
  // "GXSETH",
  // "NEOUSDT",
  // "NEOBNB",
  // "POEETH",
  // "QSPETH",
  // "BTSBTC",
  // "BTSBNB",
  // "XZCETH",
];
